### ISSUE TITLE
[Feature Request]Enable google drive shared storage to be mounted

### ISSUE THREAD

**Issue by yougeshlama** [thecoder-001/MineColab#19]
**Is your feature request related to a problem? Please describe.**
As you know the google drive has storage limit. upto 15 gb. Its not the enough amount for a minecraft server.

**Describe the solution you'd like**
By the share acess directory We can have as much as storage we want and there will be no limit of it.

**Describe alternatives you've considered**
Google Drive 
And shared drive  [_HERE_](http://td.fastio.me/)
![screen capture](https://user-images.githubusercontent.com/55014913/103213933-3ff54680-4937-11eb-9e92-136896b2ce18.png)

**Additional context**
As we can have unlimited storage using shared acess. Please make the script to able to mount google drive shared with me folder. IF possible. :)

**Comment by thecoder-001** [comment]
Hello!
That probably won't be a good idea since using shared storage with unlimited storage have the t&c which would clash with or user case. Detection of so can result in deletion of data by google, and nobody likes to lose their world. What you can do is to make another google account and fully dedicate its drive space to your Minecraft world.
