### ISSUE TITLE
[BUG] ngrok doesn't show any output

### ISSUE THREAD

**Issue by leeceeksdee** [thecoder-001/MineColab#2]
**Describe the bug**
ngrok doesn't seem to be showing any output, almost like if it didn't even run.

**To Reproduce**
Run the script that starts ngrok

**Expected behavior**
ngrok showing information such as server address.

**Minecraft server Version**
Paper 1.12.2

**Mod/Datapack list**
None

**Additional context**
Could this be happening because I excluded tmux from the list of packages that would be installed? I removed it from here because I don't see any requirement for tmux in the code.

**Comment by leeceeksdee** [comment]
Looks like this is expected. I'll send a PR that fixes this.

**Comment by thecoder-001** [comment]
Yes, this was an expected behavior. The user was earlier required to go to https://dashboard.ngrok.com/status/tunnels and get the IP address from there.With the latest commit (2a53fcf103e9601b3d120774e4ab78e9668e32db) I have now added code so that the IP address in outputted into the notebook console itself. 
Thanks for informing.

**Comment by leeceeksdee** [comment]
I think I (kind of) fixed it in a better way, could you take a look at https://github.com/thecoder-001/MineColab/pull/3?
