### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cs0ki** [thecoder-001/MineColab#20]
**Describe the bug**

**To Reproduce**
Using a 1.12.2 forge
**Expected behavior**
split up error code
with mods and without mod is same results
![image](https://user-images.githubusercontent.com/50553079/103437451-2fd7b280-4c28-11eb-8153-b5394520e6b6.png)

**Comment by thecoder-001** [comment]
Hello!
This is due to using java version 15 by default which works fine for newer versions of Minecraft but causes problems in older versions. Plan of including a config to change this easily is expected soon (though is unfortunately getting regularly delayed because of my lack of time), but for now you can edit the following line and change `15` to `8` to fix the issue.

![Screen Shot 2021-01-01 at 4 50 44 PM](https://user-images.githubusercontent.com/25097841/103437783-c1a7e580-4c51-11eb-821d-497c35bde3fe.png)

PS: factory reset the runtime if any problems persist. Don't worry, this won't delete any world data.
![Screen Shot 2021-01-01 at 4 54 48 PM](https://user-images.githubusercontent.com/25097841/103437815-12b7d980-4c52-11eb-9d04-239a5303b6f0.png)

**Comment by Cs0ki** [comment]
still the same
![yeah](https://user-images.githubusercontent.com/50553079/103447595-9c38cd00-4c8d-11eb-99d7-d46281704eb3.png)

**Comment by infinitygamer404** [comment]
Remove everything after ```# Update the package lists``` to the line before ```# Mount drive``` with 
```
# Update the package lists
!sudo apt update &>/dev/null && echo "apt cache successfully updated" || echo "apt cache update failed, you might receive stale packages"
# Install OpenJDK 8
!sudo apt-get install openjdk-8-jdk &>/dev/null && echo "Yay! Openjdk8 has been successfully installed." || echo "Failed to install OpenJdk8."

#Perform java version check
java_ver = !java -version 2>&1 | awk -F[\"\.] -v OFS=. 'NR==1{print $2}'

!sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
!export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/
!export PATH=$PATH:$JAVA_HOME
print(java_ver)
```
And it should work.

**Comment by orangemn6** [comment]
@infinitygamer404 's solution should work. Minecraft 1.12 is incompatible with java 15

**Comment by Benjimanrich** [comment]
@Cs0ki there ya go
