### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2h0oou** [thecoder-001/MineColab#29]
**Describe the bug**
![image](https://user-images.githubusercontent.com/79088241/107940897-e8349c80-6fc3-11eb-9f67-1ad426f1c002.png)
![Screenshot 2021-02-15 192817](https://user-images.githubusercontent.com/79088241/107940964-fda9c680-6fc3-11eb-8000-e36e1af12cef.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft server Version**
Specify the minecraft server version and if vanilla or modded.

**Mod/Datapack list**
List all the mods/datapacks currently being used on the server if applicable.

**Additional context**

**Comment by infinitygamer404** [comment]
@2h0oou you are trying to run an older version of minecraft right? (1.12.2 probably)
You should've included that in the bug report and explain what kind of issue it is

I think you are having the same problem as #20 
Check my comment on that issue and try it. You see, currently it installs java 15 on the colab notebook. Minecraft versions 1.12.2 and older ones don't run on java 15, they need java 8. But java 8 causes performance issues sometimes on newer versions so we use that.

**Comment by infinitygamer404** [comment]
Please try to put more effort into creating an issue and reporting the bug properly, don't just blindly create an issue because of an error, try a few solutions yourself and look if any other issues match your situation and try those solutions if there are any.
Try to include at least the minecraft version and the description of the bug. And title the issue appropriately. This goes for everyone

**Comment by thecoder-001** [comment]
Closing now. Feel free to reopen if the issue still remains unresolved.
