### ISSUE TITLE
[BUG] Not Working Anymore

### ISSUE THREAD

**Issue by LeroyWasKilled** [thecoder-001/MineColab#6]
The server is not working anymore.

**Comment by thecoder-001** [comment]
Hello!
Thanks for submitting a bug report. Looks like ngrok is causing issues and dropping the connection.
Trying to find a workaround.
Cheers

**Comment by infinitygamer404** [comment]
bug report of the century here

**Comment by thecoder-001** [comment]
Hello again!
The issue seems to be arising from a limit imposed by ngrok. I haven't been able to find where its documented or what the limit actually is, but you can get around it by creating another ngrok account. For the time being, keep switching between those accounts as a workaround.
I'm planning to add more options in future with hopefully higher limits.
Cheers
