### ISSUE TITLE
[BUG] Did colab stopped people from hosting server?

### ISSUE THREAD

**Issue by sudo216** [thecoder-001/MineColab#62]
**Describe the bug**
The colab is not connecting to its backend.

**To Reproduce**
1. Go to colab
2. Click on start server
3. See error

**Expected behavior**
I thought server would run.

**Screenshots**
![image](https://user-images.githubusercontent.com/55014913/145817229-85468cd2-3722-4de0-8cfa-efde791ec0e7.png)

**Minecraft server Version**
1.16.5

**Mod/Datapack list**
paper 

**Additional context**

**Comment by thecoder-001** [comment]
Oops...sorry for the late response. I thought it might have been due to high traffic at that time, but if you're still not able to access it maybe its something else.
For me, it seems to be working just fine (tested just now). As a wild guess...maybe try with a vpn or use a temporary account to check if google hasn't flagged you for some reason?

**Comment by sudo216** [comment]
yah I had tried hosting in 3 different acc but i could only play for a while and the server automatically shut's off and say's Sorry No backend available.Please try again and Even I tried after 2 to 3 days it still says that
:(
