### ISSUE TITLE
[BUG] Ngrok Not accepting authtoken and changing drives fails

### ISSUE THREAD

**Issue by orangemn6** [thecoder-001/MineColab#9]
**Describe the bug**
When I try to run the scripts, it wont accept the ngrok authtoken
**To Reproduce**
1. Run the script on google colab
2. put in my ngrok  authtoken
3. error

**Expected behavior**
For it to successfuly connect to ngrok

**Screenshots**

**Minecraft server Version**
All

**Comment by thecoder-001** [comment]
Hello! 
It seems to be working for me. Maybe you didn't pasted the correct auth token? Can you please try again and include a screenshot of the error so that I can see what's really going on?

![Screen Recording 2020-12-05 at 9 21 54 PM](https://user-images.githubusercontent.com/25097841/101247569-4c272300-3740-11eb-9025-097c5da56301.gif)

Cheers

**Comment by orangemn6** [comment]
yes I fixed the issue. now when my friends try to join it doesnt work + I cant ssh @thecoder-001

**Comment by orangemn6** [comment]
also I get this error when joining server:
![Screenshot_2020-12-05-40_1060x478](https://user-images.githubusercontent.com/60720126/101265354-a52c9200-3713-11eb-8136-c4954c988753.png)

**Comment by thecoder-001** [comment]
Hi!
Are you still experiencing the issue? It looks like you were entering the wrong ngrok ip while trying to connect. You can check for the correct ip from either the console or from the [tunnel list](https://dashboard.ngrok.com/status/tunnels) in ngrok's dashboard.
Cheers

**Comment by orangemn6** [comment]
Thanks! I was using the url it gave me in the output. is that wrong?

**Comment by thecoder-001** [comment]
Closing as stale.
